version: "3.8"
services:
  backend:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app

  frontend:
    build: .
    container_name: streamlit_app
    ports:
      - "8501:8501"
    command: streamlit run frontend.py --server.port 8501 --server.address 0.0.0.0
    volumes:
      - .:/app
    depends_on:
      - backend